main:
  push:
    - name: "同步到 GitHub"
      imports: https://cnb.cool/dmxapi/claude-code-my/-/blob/main/env.yml
      runner:
        tags: cnb:arch:amd64
        cpus: 1
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/YeSongYun/clawdbot-cn.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            force: true